{
    "name": "Havano All In One",
    "version": "19.0.1.0.9",
    "category": "Sales",
    "summary": "Havano suite: duplicates, contacts, pharmacy products, doctors, tax pricing, PDF preview",
    "author": "Havano",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "contacts",
        "product",
        "uom",
        "sale_management",
        "purchase",
        "account",
        "stock",
    ],
    "data": [
        "security/havano_user_roles.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/design_templates.xml",
        "views/webclient_templates_left.xml",
        "views/webclient_templates_middle.xml",
        "views/webclient_templates_right.xml",
        "data/modern_preview_templates.xml",
        "data/normal_preview_templates.xml",
        "data/old_standard_preview_templates.xml",
        "reports/modern_invoice_templates.xml",
        "reports/normal_invoice_templates.xml",
        "reports/old_standard_invoice_templates.xml",
        "reports/preview_layout_report_templates.xml",
        "reports/report_invoice_templates.xml",
        "reports/fresh_layout_templates.xml",
        "reports/trucking_invoice_templates.xml",
        "reports/report_sale_templates.xml",
        "views/invoice_template_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/res_partner_menus.xml",
        "views/multi_uom_views.xml",
        "views/sale_purchase_views.xml",
        "views/stock_config_settings_views.xml",
        "views/pharmacy_views.xml",
        "views/product_views.xml",
        "views/product_pricelist_views.xml",
        "views/res_users_views.xml",
        "views/preview_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "havano_all_in_one/static/src/js/preview_button.js",
            "havano_all_in_one/static/src/scss/preview_style.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
