from . import pharmacy_dosage
from . import hao_bank_detail
from . import res_company
from . import res_config_settings
from . import account_account
from . import res_partner
from . import res_users
from . import sale_order
from . import purchase_order
from . import account_move
from . import product_template
from . import product_pricelist_item
from . import sale_order_line
from . import invoice_template
from . import report_preview_pdf
from . import ir_attachment
from . import item_profitability_report
from . import category_profitability_report
from . import daily_sales_report
from . import sales_return_report
from . import account_report
from . import financial_ratio
